# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestHoops():
  def setup_method(self, method):
    self.driver = webdriver.Edge()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_hoops(self):
    self.driver.get("https://aka.ms/pikachu")        
    self.driver.set_window_size(1936, 1048)
    time.sleep(20)  # Add time sleep here
    
    tableinfo = self.driver.find_element(By.CSS_SELECTOR, "tbody").text
    print(tableinfo)
  
test = TestHoops()
test.setup_method(None)
test.test_hoops()
